#!/bin/bash -e
set -e

APP="$1"; IMAGE="dokku/$APP"
echo "-----> Injecting ffmpeg ..."

FFMPEG_PATH="/usr/local/bin/ffmpeg"
FFPROBE_PATH="/usr/local/bin/ffprobe"
X264_PATH="/usr/local/bin/x264"
X264H_PATH="/usr/local/include/x264.h"
X264CONFIG_PATH="/usr/local/include/x264_config.h"
X264PC_PATH="/usr/local/lib/pkgconfig/x264.pc"
LIBX264SO_PATH="/usr/local/lib/libx264.so"
LIBX264A_PATH="/usr/local/lib/libx264.a"

COMMAND=$(cat <<EOF
export DEBIAN_FRONTEND=noninteractive
if [ ! -x $FFMPEG_PATH ]; then
    apt-get install -y libmp3lame-dev libass-dev libx264-dev
    wget --quiet -O $FFMPEG_PATH https://github.com/mattcodez/dokku-ffmpeg/raw/master/binaries/ffmpeg
    chmod 755 $FFMPEG_PATH
    echo "       Injected ffmpeg"
    wget --quiet -O $FFPROBE_PATH https://github.com/mattcodez/dokku-ffmpeg/raw/master/binaries/ffprobe
    chmod 755 $FFPROBE_PATH
    echo "       Injected ffprobe"

    wget --quiet -O $X264_PATH https://github.com/mattcodez/dokku-ffmpeg/raw/master/binaries/x264
    chmod 755 $X264_PATH
    echo "       Injected x264"
    wget --quiet -O $X264H_PATH https://github.com/mattcodez/dokku-ffmpeg/raw/master/binaries/x264.h
    chmod 644 $X264H_PATH
    echo "       Injected x264.h"
    wget --quiet -O $X264CONFIG_PATH https://github.com/mattcodez/dokku-ffmpeg/raw/master/binaries/x264_config.h
    chmod 644 $X264CONFIG_PATH
    echo "       Injected x264_config.h"
    mkdir "/usr/local/lib/pkgconfig"
    wget --quiet -O $X264PC_PATH https://github.com/mattcodez/dokku-ffmpeg/raw/master/binaries/x264.pc
    chmod 644 $X264PC_PATH
    echo "       Injected x264.pc"
    wget --quiet -O $LIBX264SO_PATH https://github.com/mattcodez/dokku-ffmpeg/raw/master/binaries/libx264.so
    chmod 755 $LIBX264SO_PATH
    echo "       Injected libx264.so"
    wget --quiet -O $LIBX264A_PATH https://github.com/mattcodez/dokku-ffmpeg/raw/master/binaries/libx264.a
    chmod 644 $LIBX264A_PATH
    echo "       Injected libx264.a"
    ranlib $LIBX264A_PATH
    ldconfig
fi
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
ID=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $ID
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null
